// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASl23ElfEMr8xOt9evqFIsMWQ2d9QpBJI',
    appId: '1:36198676215:web:3c7ea13753b95d947585f2',
    messagingSenderId: '36198676215',
    projectId: 'idfk-70bf3',
    authDomain: 'idfk-70bf3.firebaseapp.com',
    storageBucket: 'idfk-70bf3.firebasestorage.app',
    measurementId: 'G-4VM48W74DM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFMPyi0wvxZ6EKGv2PDOkX6fjNzOxASO4',
    appId: '1:36198676215:android:58d2863322efa9757585f2',
    messagingSenderId: '36198676215',
    projectId: 'idfk-70bf3',
    storageBucket: 'idfk-70bf3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDb3qjkM_qyLlldE8YX5tDp8e-sH9ivYQs',
    appId: '1:36198676215:ios:0cc11d268e49e3197585f2',
    messagingSenderId: '36198676215',
    projectId: 'idfk-70bf3',
    storageBucket: 'idfk-70bf3.firebasestorage.app',
    iosBundleId: 'com.example.ic16',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDb3qjkM_qyLlldE8YX5tDp8e-sH9ivYQs',
    appId: '1:36198676215:ios:0cc11d268e49e3197585f2',
    messagingSenderId: '36198676215',
    projectId: 'idfk-70bf3',
    storageBucket: 'idfk-70bf3.firebasestorage.app',
    iosBundleId: 'com.example.ic16',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASl23ElfEMr8xOt9evqFIsMWQ2d9QpBJI',
    appId: '1:36198676215:web:0ec0ebfeee104fe67585f2',
    messagingSenderId: '36198676215',
    projectId: 'idfk-70bf3',
    authDomain: 'idfk-70bf3.firebaseapp.com',
    storageBucket: 'idfk-70bf3.firebasestorage.app',
    measurementId: 'G-6L614PQEDS',
  );
}
